version: '2'

services:
    mysql:
        image: 'mysql'
        container_name: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 1234
        networks:
          - db
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment: 
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: 1234
        networks:
          - db
        ports:
          - 8888:80

networks:
    db:
      name: db
      driver: bridge

volumes:
    db-data: