version: '2'

services:
    phpfpm:
        image: 'php:fpm'
        container_name: php-fpm
        networks:
          - front
          - db
        volumes:
          - ./html:/var/www/html
        command:  bash -c "docker-php-ext-install mysqli && php-fpm"
          
    nginx:
        image: 'nginx'
        container_name: nginx
        networks:
          - front
        ports:
          - '80:80'
        volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf
          - ./html:/usr/share/nginx/html

networks:
    front:
      name: front
      driver: bridge
    db:
      name: db
      driver: bridge